// Decides, from a key's name and value, whether it is a secret (-> 1Password),
// a plain setting (-> committed template), production (-> excluded), or
// machine-generated (-> left alone). Unknown means secret: a setting stored in
// the vault is harmless; a secret committed to git is not.
import { URL } from 'node:url';

const GENERATED = new Set(['VERCEL_OIDC_TOKEN']);
const PROD_NAME = /(^|_)(PROD|PRODUCTION)(_|$)/;
const DB_SCHEME = /^(postgres(ql)?|redis|rediss|mysql|mariadb|mongodb(\+srv)?|amqps?):\/\//i;
const DB_NAME = /(^|_)(DATABASE_URL|DB_URL|REDIS_URL|MONGO(DB)?_URI|CONNECTION_STRING)$/;
const LITERAL_EXACT = new Set(['PORT', 'HOST', 'NODE_ENV', 'LOG_LEVEL', 'TZ', 'ENV']);
const STRONG_LITERAL = /_(PATH|FILE|DIR|URL|URI|HOST|HOSTNAME|PORT|REGION|BUCKET|ENV|LEVEL|MODE|PREFIX|DOMAIN|ORIGIN|ENDPOINT|ENABLED|MAX|MIN|MS|TIMEOUT|VERSION)$/;
const WEAK_LITERAL = /_(ID|NAME)$/;
const SECRET_WORD = /(^|_)(KEY|SECRET|TOKEN|PASSWORD|PASSWD|PASS|PWD|DSN|CREDENTIALS?|PRIVATE|SALT|SIGNING|CERT)(_|$)/;
const LOCAL_HOSTS = new Set(['localhost', '127.0.0.1', '::1', '[::1]', '0.0.0.0', 'host.docker.internal']);
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const SECRETISH = [
  /^(sk|rk|pk)_(test|live)_/, /^whsec_/, /^AKIA[0-9A-Z]{16}$/, /^re_[A-Za-z0-9]{8,}/, /-----BEGIN/,
  /:\/\/[^/\s:@]+:[^@\s]+@/, /^gh[pousr]_/, /^xox[abpr]-/, /^eyJ[A-Za-z0-9_-]{8,}\./,
];
const PLAIN = /^(true|false|yes|no|on|off|-?\d+(\.\d+)?|[A-Za-z0-9._:/@,-]{1,40})$/i;

export function looksSecret(v) {
  if (SECRETISH.some((re) => re.test(v))) return true;
  return v.length >= 24 && /^[A-Za-z0-9+/=_-]+$/.test(v) && /\d/.test(v) && /[A-Za-z]/.test(v) && !UUID.test(v);
}

function localHost(h) {
  h = (h || '').toLowerCase();
  return LOCAL_HOSTS.has(h) || h.endsWith('.local') || h.endsWith('.localhost') || (h !== '' && !h.includes('.') && !h.includes(':'));
}

export function productionReason(key, value) {
  if (PROD_NAME.test(key)) return 'name says production';
  if (value.includes('_live_')) return 'live-mode key';
  if (DB_SCHEME.test(value)) {
    let host;
    try { host = new URL(value).hostname; } catch { return 'database URL could not be parsed'; }
    if (!localHost(host)) return 'database on a non-local host';
  }
  return null;
}

/** -> { kind: 'secret' | 'literal' | 'excluded' | 'skipped', reason } */
export function classify(key, value, { include = false } = {}) {
  if (GENERATED.has(key)) return { kind: 'skipped', reason: 'machine-generated by another tool' };
  const prod = productionReason(key, value);
  if (prod && !include) return { kind: 'excluded', reason: prod };
  if (DB_SCHEME.test(value) || DB_NAME.test(key)) return { kind: 'secret', reason: 'connection string' };
  if (LITERAL_EXACT.has(key) || STRONG_LITERAL.test(key)) {
    return looksSecret(value) ? { kind: 'secret', reason: 'value looks secret' } : { kind: 'literal' };
  }
  if (WEAK_LITERAL.test(key) && !SECRET_WORD.test(key.replace(WEAK_LITERAL, ''))) {
    return looksSecret(value) ? { kind: 'secret', reason: 'value looks secret' } : { kind: 'literal' };
  }
  if (SECRET_WORD.test(key)) return { kind: 'secret' };
  if (looksSecret(value)) return { kind: 'secret', reason: 'value looks secret' };
  if (PLAIN.test(value)) return { kind: 'literal' };
  return { kind: 'secret', reason: 'unrecognised, kept secret to be safe' };
}
